name: Shellcheck

on:
  pull_request:
    paths:
      - '**.bash'
  push:
    branches:
      - main
    tags-ignore:
      - '**'
    paths:
      - '**.bash'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Run shellchecker
        run: |
          shellcheck --shell=bash scripts/*.bash
